# coding: utf-8

"""
    Echo example

    A simple API to echo back messages.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.echo import Echo  # noqa: E501
from swagger_client.rest import ApiException


class TestEcho(unittest.TestCase):
    """Echo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcho(self):
        """Test Echo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.echo.Echo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
