# coding: utf-8

"""
    Echo example

    A simple API to echo back messages.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_model import ErrorModel  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorModel(self):
        """Test ErrorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_model.ErrorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
